### PR TITLE
[matsubara] Product of matsubaras, additional gf product test

### PR DESCRIPTION
**Pull request by Wentzell**
-Implemented product of two matsubara frequencies to yield a complex
-Added a test that calculates and checks the product of two gfs

### CODE REVIEW

**Comment by parcollet** [comment]
Great.
Should we at some point (not now) get rid of this CRTP for the mesh point operators ?

**Comment by parcollet** [comment]
Can you merge the test of #444 with this ?

**Comment by Wentzell** [comment]
Yeah, maybe we can just put all the operators directly into matsubara? The only special cases are
addition and subtraction right? In every other case we expect a cast to dcomplex.

**Comment by Wentzell** [comment]
I merged the tests of #444 into gf_prod.hpp

However, looking at the output of the test, it seems that the tails are not set at all?
```
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from Gf
[ RUN      ] Gf.ProdGfTail
 Tail of G 
 empty tail

 Tail of product G*G 
 empty tail

 Expected Tail 
 empty tail

[       OK ] Gf.ProdGfTail (6 ms)
[ RUN      ] Gf.AutoAssignMatrixGf2_product
[       OK ] Gf.AutoAssignMatrixGf2_product (1 ms)
[ RUN      ] Gf.AutoAssignMatrixGf2_sum_product
[       OK ] Gf.AutoAssignMatrixGf2_sum_product (1 ms)
[----------] 3 tests from Gf (8 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (8 ms total)
[  PASSED  ] 3 tests.
```
How can this be?

**Comment by parcollet** [comment]
Because this is a serious bug in the tail !
t = omega + 0 + 0/omega + ....
t*t =  omega ^2 ...
t*t*t = omega ^ 3 ? 
BUT the _tail type is truncated at omega^2, so the omega^3 is dropped, so 
t*t*t = 0 !, 
which inverse is undefined, hence "empty tail" or nan...

The tail nightmare again : 
@mferrero : since you are in charge of the tails, what do we do ?

**Comment by parcollet** [comment]
Ok, the issue with tail is moved to an issue.

**Pull request merged**
