### PR TITLE
Add basic jenkins support with ubuntu build

### PR DESCRIPTION
**Pull request by dylex**
This is just a simple jenkins build of triqs on ubuntu xenial to start with.

Currently the build is successful, but there are a few failing tests -- not sure if these are expected (perhaps because not running under mpi):
```
[ubuntu] 95% tests passed, 11 tests failed out of 210
[ubuntu] 
[ubuntu] Total Test time (real) =  40.26 sec
[ubuntu] 
[ubuntu] The following tests FAILED:
[ubuntu] 	 25 - ising2d (Failed)
[ubuntu] 	 29 - mpi_vector_np2 (Failed)
[ubuntu] 	 30 - mpi_vector_np3 (Failed)
[ubuntu] 	 31 - mpi_vector_np4 (Failed)
[ubuntu] 	 33 - mpi_gf_np2 (Failed)
[ubuntu] 	 34 - mpi_gf_np3 (Failed)
[ubuntu] 	 35 - mpi_gf_np4 (Failed)
[ubuntu] 	 37 - mpi_array_np2 (Failed)
[ubuntu] 	 38 - mpi_array_np3 (Failed)
[ubuntu] 	 39 - mpi_array_np4 (Failed)
[ubuntu] 	 40 - comm_split_np4 (Failed)
```

From [flatiron internal jenkins](https://jenkins.flatironinstitute.org/job/TRIQS/job/triqs/job/jenkins/).

### CODE REVIEW

**Comment by parcollet** [comment]
Hi Dylan, 

Thank you. 
No the tests should not fail, it looks like an MPI issue.

@Wentzell  : can you have a look tomorrow ?
I guess the point is just to pick the docker file, run the install, and 
get the error message from MPI ?

The logs of Jenkins do not give much information.

Olivier

**Comment by parcollet** [comment]
PS : 
normally these tests should be run by 
mpirun -np xx the_test
Can we recover the current docker image (with everything compiled) from Jenkins ??

**Comment by Wentzell** [comment]
These test failures are because inside the docker image you are root, as whom you cannot execute mpirun/mpiexec

```bash
sudo mpiexec

--------------------------------------------------------------------------
mpiexec has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run mpiexec as a non-root user.

You can override this protection by adding the --allow-run-as-root
option to your command line.  However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------
```

**Comment by dylex** [comment]
Ah, they're actually running as the jenkins user, but that pointed me in the right direction -- mpirun tries to look up your uid but it didn't exist in the container.  Importing the passwd entry fixed it, and now all tests pass.

@parcollet, there should be full logs inside each build under "console logs". Currently builds are run on an isolated jenkins build vm, but we could find another machine you have access to to run them on if you want to look directly at the resulting docker images.

**Comment by dylex** [comment]
Added CentOS7 as well (with gcc-7, because there's not a good package of llvm 5.0 yet, just 4), with all tests passing.

**Comment by dylex** [comment]
Continuing on jenkins branch.

**Pull request closed without merging**
