### PR TITLE
[doc] triqs includes to c++2rst

### PR DESCRIPTION
**Pull request by HugoStrand**
`c++2rst` needs the include paths for `triqs`, here is one solution to get them from the `triqs` target.

Please merge

### CODE REVIEW

**Comment by parcollet** [comment]
Ok, that is the idea.
@Wentzell 

INCLUDE_DIRECTORIES is the *public* or *private* flags ?
Isn't rather INTERFACE_INCLUDE_DIRECTORIES
?
Cf 
https://cmake.org/cmake/help/latest/command/target_include_directories.html#command:target_include_directories

**Comment by Wentzell** [comment]
INCLUDE_DIRECTORIES contains both the public and the private directories.

The INTERFACE_INCLUDE_DIRECTORIES could be used by the applications using triqs and
would contain the headers in the **installed** location (but it is currently).
Note however that the usage of INTERFACE_INCLUDE_DIRECTORIES is not necessary since
triqsvars.sh is already setting the proper CPATH.

Either way INTERFACE_INCLUDE_DIRECTORIES could not be used before the actual installation.

**Comment by HugoStrand** [comment]
```
get_property(TRIQS_INCLUDE_DIRS TARGET triqs PROPERTY INCLUDE_DIRECTORIES) message(STATUS "TRIQS_INCLUDE_DIRS = ${TRIQS_INCLUDE_DIRS}") string (REPLACE ";" "\n--includes " TRIQS_INCLUDE_DIRS_STR "${TRIQS_INCLUDE_DIRS}") set( TRIQS_INCLUDE_DIRS_STR "--includes ${TRIQS_INCLUDE_DIRS_STR}" )
```

**Comment by Wentzell** [comment]
Already fixed in the current unstable branch

**Pull request closed without merging**
