### PR TITLE
UBSAN sanitization build in jenkins and related fixes

### PR DESCRIPTION
**Pull request by dylex**
Check jenkins status before merging.

### CODE REVIEW

**Comment by dylex** [comment]
This is ready.

**Comment by Wentzell** [comment]
Hey Dylan,

Thanks a lot!

Why do we build libc++ and libc++abi instead of using the ubuntu packages in that case?

https://packages.ubuntu.com/bionic/libc++-dev
https://packages.ubuntu.com/bionic/libc++abi-dev

**Comment by dylex** [comment]
I just copied that from our existing ubuntu build, but probably a good point to eliminate duplication, at least.

I think that originally came from xenial which didn't have those packages at the time. We may be able to switch the ubuntu-clang build over now. I'll give it a try.

**Comment by Wentzell** [comment]
@dylex Do you have an idea whats going wrong with the jenkins osx builds?

**Comment by dylex** [comment]
Not exactly, but it looks unrelated to this stuff. It looks like it did some automatic updates and rebooted last night around that time, so maybe it was a shutdown process killing things. It's running fine now.

**Pull request merged**
