### PR TITLE
[array] make ref_counters std::atomic

### PR DESCRIPTION
**Pull request by HugoStrand**
Fix to make gf_views thread safe using std::atomic on the reference counters.

### CODE REVIEW

**Comment by parcollet** [comment]
That is what I meant indeed. Does it fix the issue ?

**Comment by parcollet** [comment]
PS : 
the concern here can be performance. Years ago, I ruled out using std::shared_ptr, 
which does exactly that, because it degraded performance in some cases.
But I was using shared_view way too much, so maybe it is not relevant any more...
To be checked.

**Comment by HugoStrand** [comment]
This fixes the segfaults in #626 . I have no idea about performance, but taking views should imho be thread safe.

**Comment by HugoStrand** [comment]
The errors from the IC are now fixed. Thanks @dylex ! @parcollet can we merge?

**Pull request merged**
