### PR TITLE
Install modulefile for the module command

### PR DESCRIPTION
**Pull request by krivenko**
Install a TCL modulefile similar to `triqsvars.sh`. It can be used for easy integration with the module systems on HPC machines.

*N.B.* Now that applications are allowed to be installed under different prefixes, they could provide their own modulefiles.

### CODE REVIEW

**Comment by parcollet** [comment]
Great.
Is it the file needed for the "module" command ?
Indeed, we will need one per repository : 
- cpp2y (which must be loaded in triqs module, right ?)
- cthyb, ctint, and co.

**Comment by krivenko** [comment]
>  Is it the file needed for the "module" command ?

Yes.

> cpp2y (which must be loaded in triqs module, right ?)

Oh, that's right.
The triqs module must then be updated to include `prereq cpp2py` instruction.

**Comment by parcollet** [comment]
Ok, to be updated then.

**Comment by Wentzell** [comment]
merged, cf. 1b8eae29d92037b64fcd1ac9460c613a8c8f6aa4 and b997c3c6470d0b38b16d4ff37fdad2f6f07247cf

**Pull request closed without merging**
