### PR TITLE
 added sum_of_elements to minivector

### PR DESCRIPTION
**Pull request by Wentzell**
Necessary for the nfft buffer that is currently beeing added to the ctint / cthyb

### CODE REVIEW

**Comment by krivenko** [comment]
Hi Nils,
There is a typo in your commit, `T=0 res`...

**Comment by Wentzell** [comment]
Sorry, fixed.

**Comment by parcollet** [comment]
Ok. Can you rename it to 
friend sum(mini_vector const & ...) ....
the product_of_elements is not a nice name either.
I will partially replace this by std::array in dev.

**Comment by Wentzell** [comment]
I changed it, however I did it with a template function and some forward declarations.
The problem is that if you need to make it visible to the triqs::utility namespace, which is non possible
if you only do it with a non-template member function. 

See also 'Approach 3' in http://web.mst.edu/~nmjxv3/articles/templates.html

**Comment by Wentzell** [comment]
Updated. This is cleaner with a non-template friend, but we need to fix the sum in algorithms.hpp with it.

**Comment by parcollet** [comment]
Merged in dev

**Pull request closed without merging**
